"""
Django settings for the_fiction_archive project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-t&_3+w%)d-5btg_=9-u%3m))0iupj)*xzqt-n5d$4#nd!v43r9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

# INSTALLED_APPS lists all Django apps that are enabled for this project.
INSTALLED_APPS = [
    'django.contrib.admin', # The admin interface site
    'django.contrib.auth',  # Core authentication framework and default models
    'django.contrib.contenttypes',
    'django.contrib.sessions',  # Session framework
    'django.contrib.messages',
    'django.contrib.staticfiles',  # Static file serving infrastructure
    "crispy_forms", # A popular app for easily styling Django forms
    "crispy_bootstrap5",    # Renders crispy forms using Bootstrap 5 framework classes
    'blog', # Custom app for blog functionality
    'accounts', # Custom app for user authentication/profile management
]


# These components process requests before hitting the views and responses leaving 
# the server.
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Defines the main URL configuration file (e.g., project_name/urls.py)
ROOT_URLCONF = 'the_fiction_archive.urls'

# TEMPLATES configures Django's template engine(s).
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # DIRS specifies directories where Django should look for templates
        # that are not inside app directories
        'DIRS': [BASE_DIR / 'templates'],
        # APP_DIRS set to True tells Django to look for 'templates/' directories inside individual apps
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'the_fiction_archive.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation'
        '.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# The URL prefix for static files when served in development or production
STATIC_URL = 'static/'
# Directories to search for static files in addition to the per-app static/ directories
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# URL to redirect to after a user logs in successfully
LOGIN_REDIRECT_URL = "home"
# URL to redirect to after a user logs out successfully
LOGOUT_REDIRECT_URL = "home"
# The URL where requests are redirected for login if required by a login_required(
LOGIN_URL = "login"

# Lists which front-end frameworks (template packs) are allowed for crispy forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
# Sets the default template pack to use for rendering all crispy forms in the project
CRISPY_TEMPLATE_PACK = "bootstrap5"
